- name:  CHR setting
  hosts: chr
  tasks:
    - name: user_add
      routeros_command:
        commands:
          - /user add name=chr_user group=read password=253166

    - name: ntp_client
      routeros_command:
        commands:
          - /system ntp client set enabled=yes server=0.ru.pool.ntp.org

    - name: routing_ospf
      routeros_command:
        commands:
          - /interface bridge add name=loopback
          - /ip address add address=172.66.0.1 interface=loopback network=172.66.0.1
          - /routing id add disabled=no id=172.66.0.1 name=OSPF_ID select-dynamic-id=""
          - /routing ospf instance add name=ospf-1 originate-default=always router-id=OSPF_ID
          - /routing ospf area add instance=ospf-1 name=backbone
          - /routing ospf interface-template add area=backbone auth=md5 auth-key=admin interface=ether1

    - name: get_facts
      routeros_facts:
        gather_subset:
          - interfaces
      register: output_ospf

    - name: print_output
      debug:
        var: "output_ospf"
